# Generated by Django 6.0.1 on 2026-09-10 17:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0002_barterrequest_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barterrequest',
            name='meeting_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
