# Generated by Django 6.0.1 on 2026-03-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_reset_otp_user_reset_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_balance',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
