# Generated by Django 6.0.1 on 2026-03-17 03:16

from django.db import migrations


def backfill_credits(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(time_balance=0.00).update(time_balance=5.00)

def reverse_backfill(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_time_balance'),
    ]

    operations = [
        migrations.RunPython(backfill_credits, reverse_backfill),
    ]
