# Generated by Django 6.0.1 on 2026-06-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Design', 'Design'), ('Development', 'Development'), ('Writing', 'Writing'), ('Music', 'Music')], default='Development', max_length=50),
        ),
    ]
